AllCops:
  NewCops: enable

Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - config/routes.rb
  Max: 50
Metrics/MethodLength:
  Max: 25
Lint/RescueException:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
